# Generated by Django 5.2.3 on 2025-06-22 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0004_productcategory_product_model_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchase_price',
            new_name='product_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_models', to='stock_app.purchase'),
        ),
    ]
