# Generated by Django 5.1.4 on 2025-07-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0006_alter_product_model_name_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='model_name',
            new_name='product_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_number',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
