# Generated by Django 5.1.4 on 2025-07-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_remove_product_product_date_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_price',
            new_name='salling_price',
        ),
    ]
