# Generated by Django 5.1.4 on 2025-07-09 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0009_rename_sale_price_product_salling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='loss',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
    ]
