# Generated by Django 5.1.4 on 2025-07-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0011_extrasale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrasale',
            name='product',
            field=models.CharField(max_length=600),
        ),
    ]
