# Generated by Django 5.1.4 on 2025-07-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0012_alter_extrasale_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.CharField(max_length=500)),
                ('expense_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
