# Generated by Django 5.1.4 on 2025-07-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0013_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='sale_date',
            new_name='expense_date',
        ),
    ]
